language: node_js

cache:
  yarn: false
  directories:
    - node_modules

before_install:
  - npm i -g yarn@latest

env:
  global:
    - HOST=0.0.0.0

install:
  - yarn install --frozen-lockfile

matrix:
  include:
    - node_js: '12'
      name: 'Test on Node.js 12'
      if: branch =~ /(master|staging|trying|v\d+\.x)/ AND NOT branch =~ /\.tmp$/
      script: 'yarn test --maxWorkers=2 --ci'
      env:
        - CACHE_NAME=node-v12
    - node_js: 'node'
      name: 'Test on Node.js latest "current"'
      if: NOT branch =~ /\.tmp$/
      before_script:
        - 'yarn lint'
      script: 'yarn test --maxWorkers=2 --ci'
      env:
        - CACHE_NAME=node-latest
    - node_js: 'lts/*'
      name: 'Canarist test on Node.js latest lts'
      if: branch =~ /(master|staging|trying|v\d+\.x)/ AND NOT branch =~ /\.tmp$/
      script: 'yarn canarist'
      env:
        - CACHE_NAME=canary
